services:
  app:
    image: jellyfin-gallery:2.1.0
    container_name: frontend

    command: ['quasar', 'dev']
    ports:
      - '9000:9000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
